version: '3.8'

volumes:
    postgres-database:
    public-storage:

services:
    php:
        container_name: ${PHP_CONTAINER_NAME}
        env_file: ${PHP_CONTEXT_DIR}/.php.env
        build:
            context: ${PHP_CONTEXT_DIR}
            dockerfile: Dockerfile
        volumes:
            - ${PHP_VOLUME_DIR}:/var/www
            - "public-storage:/var/www/storage/app/public"
    nginx:
        container_name: ${NGINX_CONTAINER_NAME}
        ports:
            - "${NGINX_CONTAINER_PORT}:80"
        networks:
            default:
                aliases:
                    - nginx
        build:
            context: ${NGINX_CONTEXT_DIR}
            dockerfile: Dockerfile
        volumes:
            - ${NGINX_VOLUME_DIR}:/var/www
        depends_on:
            - php
    postgres:
        container_name: ${POSTGRES_CONTAINER_NAME}
        ports:
            - "${POSTGRES_CONTAINER_PORT}:5432"
        image: postgres
        tty: true
        env_file: postgres/.postgres.env
        volumes:
            - "postgres-database:/var/lib/postgresql/data"
    redis:
        image: redis:4.0
        container_name: ${REDIS_CONTAINER_NAME}
        ports:
            - "${REDIS_CONTAINER_PORT}:6379"
        command: [ "redis-server", "--bind", "0.0.0.0", "--port", "6379" ]
    frontend:
        container_name: ${FRONTEND_CONTAINER_NAME}
        build:
            context: ${FRONTEND_CONTEXT_DIR}
            dockerfile: Dockerfile
        stdin_open: true
        environment:
            - HOST=0.0.0.0
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - FAST_REFRESH=false
        ports:
            -   "${FRONTEND_CONTAINER_PORT}:3000"
        volumes:
            -   ${FRONTEND_VOLUME_DIR}:/app
            -   /app/node_modules
        working_dir: /app
